WebPage/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebPage.Models
{
    public class ContatoModel
    {
        [Required(ErrorMessage = "O nome é obrigatório.")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O e-mail é obrigatório.")]
        [EmailAddress(ErrorMessage = "O e-mail fornecido não é válido.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "O assunto é obrigatório.")]
        public string Assunto { get; set; }

        [Required(ErrorMessage = "A mensagem é obrigatória.")]
        public string Mensagem { get; set; }
    }
}

WebPage/Models/ErrorViewModel.cs
namespace WebPage.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

WebPage/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net;
using WebPage.Models;

namespace WebPage.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contato(ContatoModel model)
        {
            if (ModelState.IsValid)
            {
                // Configuração do envio de e-mail  
                string toEmail = "messier104ngc4594@gmail.com"; 
                string subject = "Nova Mensagem de Contato via Site";
                string body = $"Nome: {model.Nome}\nEmail: {model.Email}\nAssunto: {model.Assunto}\nMensagem: {model.Mensagem}";

                // Enviar o e-mail  
                using (var message = new MailMessage("messier104ngc4594@gmail.com", toEmail))
                {
                    message.Subject = subject;
                    message.Body = body;
                    message.IsBodyHtml = false;

                    using (var smtp = new SmtpClient())
                    {
                        smtp.Host = "smtp.gmail.com"; 
                        smtp.Port = 587; 
                        smtp.Credentials = new NetworkCredential("messier104ngc4594@gmail.com", "axvz jkoe ptmy iuck"); 
                        smtp.EnableSsl = true;
                        smtp.Send(message);
                    }
                }

                TempData["SuccessMessage"] = "Mensagem enviada com sucesso!";
                ModelState.Clear();
            }

            return View("Index");
        }
    }
}

WebPage/Controllers/HomeController.cs
using Grpc.Core;
using System.IO;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebPage.Models;
using Microsoft.Extensions.Hosting.Internal;

namespace WebPage.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
    }
}

WebPage/Controllers/ProjetosController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebPage.Controllers
{
    public class ProjetosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebPage/Controllers/SobreController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebPage.Controllers
{
    public class SobreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebPage/Views/Contato/Index.cshtml
@model ContatoModel

@{
    ViewData["Title"] = "Contato";
}





<div class="container my-5 p-0">
    <div id="home" class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="container">          
            <div class="col">
                <h2 class="title d-flex justify-content-center">CONTATO</h2>
                <div class="underline mb-5"></div>
            </div>
        </div>
        <div class="container p-4">
            <div id="colum" class="card p-0 row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 ">
                <div class="col-lg-6 mb-5">
                    <div class="card w-50 mb-5">
                        <div class="card-body text-light d-flex justify-content-end" style="background-color: #086eba; font-weight:900">
                            Vamos conectar
                        </div>
                    </div>
                    @if (TempData["SuccessMessage"] != null)
                    {
                        <div class="alert alert-success" id="alert-success">
                            @TempData["SuccessMessage"]
                        </div>
                    }
                    <form asp-controller="Contato" asp-action="Contato" method="post">
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Nome" name="nome"  class="form-control" id="floatingInput" placeholder=" " required>
                            <label for="floatingInput">Seu nome</label>
                            <div class="invalid-feedback">
                                Digite um nome.
                            </div>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" asp-for="Email" name="email" class="form-control" id="floatingInput" placeholder=" " required>
                            <label for="floatingInput">Seu e-mail</label>
                            <div class="invalid-feedback">
                                Digite um email.
                            </div>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Assunto" name="assunto" class="form-control" id="floatingInput" placeholder=" " required>
                            <label for="floatingInput">Seu assunto</label>
                            <div class="invalid-feedback">
                                Digite um assunto.
                            </div>
                        </div>
                        <div class="form-floating">
                            <textarea class="form-control" asp-for="Mensagem" name="mensagem" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px" required></textarea>
                            <label for="floatingTextarea2">Mensagem</label>
                            <div class="invalid-feedback">
                                Digite uma mensagem.
                            </div>
                        </div>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-start mt-2 mb-lg-3">
                            <button type="submit" onclick="showModal()" class="btn-home">Enviar</button>
                        </div>
                    </form>                  
                </div>
                <div class="col-lg-5 m-3">
                    <h4 class="display-6">
                        Informações de contato
                    </h4>
                    <br />
                    
                    <p class="lead">
                        ​​Se você gostaria de saber mais sobre meus trabalhos e  projetos, não hesite em enviar uma mensagem. Adoraria ouvir de você e fornecer as informações que você precisa!
                    </p>
                    <br />
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-3">
                                <i class="bi bi-envelope-fill" style="font-size: 48px;"></i>
                            </div>
                            <div class="col-sm-9 mb-3">
                                <div class="row">
                                    <div class="col-8 col-sm-9">
                                        <h4>E-mail</h4>
                                        <a class="text-decoration-none" href="mailto:messier104ngc4594@gmail.com?subject=Assunto&body=Mensagem">Messier104ngc4594@gmail.com</a>
                                        <a class="text-decoration-none" href="mailto:messier104ngc4594@hotmail.com.com?subject=Assunto&body=Mensagem">Messier104ngc4594@hotmail.com</a>
                                    </div>                                  
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <i class="bi bi-geo-alt-fill" style="font-size: 48px;"></i>
                            </div>
                            <div class="col-sm-9">
                                <div class="row">
                                    <div class="col-8 col-sm-9">
                                        <h4>Endereço</h4>
                                        <p>
                                            Rua joão XXIII, Primeiro de Maio, Brusque SC, 88353530
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/js/site.js" asp-append-version="true"></script>

WebPage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}


<div  class="container my-5">
    <div id="home" class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-5 p-3 p-lg-5 pt-lg-3">
            <h4 class="H4">
                Olá , eu sou
            </h4>
            <h1 class="display-4 fw-bold lh-1 text-body-emphasis">Lucas Silva</h1>
            <p class="lead">
                Neste espaço, você encontrará uma seleção dos meus trabalhos mais significativos. Minha missão é explorar possibilidades e criar soluções. Espero que goste da visita!
            </p>
            <h5 class="H5">
                Web Designer 
            </h5>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mt-5 mb-lg-3">
                <button type="button" class="btn-home">
                    <a class="text-decoration-none text-light" target="_blank" href="https://api.whatsapp.com/send?phone=5547999756192">Contrate-Me</a>
                </button>
            </div>
        </div>
        <div class="col-lg-2 align-self-end p-0">
            <div class="icon-bar">
                <a href="https://www.linkedin.com/in/lucas-santos-93508a245/" target="_blank" class="icon">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a href="https://github.com/Messier104ngcc" target="_blank" class="icon">
                    <i class="fab fa-github"></i>
                </a>
                <a href="https://www.instagram.com/l_santos.s/" target="_blank" class="icon">
                    <i class="fas fa-user-circle"></i>
                </a>
            </div>
        </div>
        <div class="col-lg-5 offset-lg-1 p-0 overflow-hidden shadow-lg m-0">
            <img class="rounded-lg-3" src="/img/Imagem do WhatsApp de 2024-11-24 à(s) 19.53.10_4e47b554.jpg" alt="" style="width: 100%; height: 100%;">           
        </div>
    </div>
</div>

WebPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web Page</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site2.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebPage.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/heroes/">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch/css@3">
</head>
<body>
    <header class="sticky-top">
        <nav id="navegacao" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 py-3">
            <div class="container-fluid">
                <img src="/img/LOGO.png"  class="img-fluid" alt="Logo" style="width: 5%; height: 5%;" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav  flex-grow-1 h5 justify-content-center gap-3 nav-underline">
                        <li class="nav-item">
                            <a class="nav-link nav text-light" asp-area="" asp-controller="Home" asp-action="Index">INICIO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav text-light" asp-area="" asp-controller="Sobre" asp-action="Index">SOBRE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav text-light" asp-area="" asp-controller="Projetos" asp-action="Index">PROJETOS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav text-light" asp-area="" asp-controller="Contato" asp-action="Index">CONTATO</a>
                        </li>                       
                        <li class="nav-item gap-5 d-none d-md-block">
                            <a class="text-decoration-none text-light" target="_blank" href="https://api.whatsapp.com/send?phone=5547999756192"><i class="bi bi-grip-vertical justify-content-center mx-2"></i><i class="bi bi-whatsapp mx-2"></i>+55 (47) 99975 6192</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 mt-5">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../assets/js/color-modes.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebPage/Views/Sobre/Index.cshtml
@{
    ViewData["Title"] = "Sobre";
}


<div class="container my-5 p-0">  
    <div id="home" class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="container">
            <div class="col">
                <h2 class="title d-flex justify-content-center">SOBRE MIM</h2>
                <div class="underline mb-5"></div>
            </div>
        </div> 
        <div class="container p-4">
            <div id="colum" class="card p-0 row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3">
                <div class="col">
                    <img src="/img/foto.png" class="img-fluid" alt="Lucas">              
                </div>               
                <div  class="col-lg-7 m-3">
                    <h4 class="mt-4">
                        Olá , Eu sou Lucas Silva
                    </h4>
                    <br />
                    <h5 class="H5">
                        Web Designer / Programador ASP. NET / SQl Server
                    </h5>                  
                    <p class="lead">
                        ​Sou um programador apaixonado por web design e desenvolvimento frontend. 
                        Com experiência em HTML, CSS e JavaScript, crio interfaces intuitivas e responsivas que melhoram a experiência do usuário. 
                        Estou sempre atualizado com as últimas tendências e tecnologias.                        
                    </p>    
                    <p class="lead">
                        Sou estudante de Engenharia de Software e possuo cursos profissionalizante em Desenvolvimento de Sistemas e Desenvolvimento Web, 
                        com ênfase na ferramenta ASP. NET. Minha formação me proporcionou uma sólida compreensão dos conceitos de programação e desenvolvimento 
                        de aplicações. Além disso, tenho conhecimento em design gráfico, o que me permite criar interfaces atraentes e funcionais. 
                        Estou sempre em busca de novos aprendizados e desafios que me ajudem a crescer na área da tecnologia.
                    </p>
                    <p class="lead">
                        Vamos conversar sobre como posso contribuir para o seu projeto!
                    </p>                   
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start mt-5 mb-lg-3">
                        <button type="button" class="btn-home">
                            <a class="text-decoration-none text-light" href="/Arquivos/currículo.pdf" download="currículo.pdf" type="application/pdf">Baixar CV</a>
                        </button>
                    </div>
                </div>               
            </div>        
        </div>       
    </div>
</div>